name: Clone Repos, push a file and create a PR

on: 
  # push:
  #   branches: main
  workflow_dispatch:
    inputs:
      repo-name:
        description: "ui-repos/api-repos"
        # default: "ui-repos"

jobs:
  Clone_GitHub_Repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
      - name: Setup Git
        run: |
          git config --global user.email "manthanjgodhasara160901@gmail.com"
          git config --global user.name "manthanjgodhasara"
      - name: Loop over json file
        run: |
          JSON_CONTENT=$(cat repos.json)
          names=$(echo "$JSON_CONTENT" | jq -r '.["${{github.event.inputs.repo-name}}"][] | .repo')
          # names=$(echo "$JSON_CONTENT" | jq -r '.["api-repos"][] | .repo')
          # IFS=$'\n'

          cd ../../

          for repo_name in $names; do
          
          echo $repo_name
          git clone https://manthanjgodhasara:${{ secrets.ACCESS_TOKEN }}@github.com/manthanjgodhasara/$repo_name.git
          cp -r ./Clone_Repo_Workflow/Clone_Repo_Workflow/.github ./$repo_name
          cd ./$repo_name
          git checkout -b "new-file-branch2"
          git add .
          git commit -m "Added files"
          git push --set-upstream origin new-file-branch2

          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.ACCESS_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/manthanjgodhasara/$repo_name/pulls \
          -d '{"title":"Adding workflow files","body":"Added workflow files. Please accept","head":"new-file-branch2","base":"main"}' 
          
          cd ..
          done